### PR TITLE
Catalog

### PR DESCRIPTION
**Pull request by yuliia-dronova**
- [DEMO LINK](https://yuliia-dronova.github.io/layout_catalog/)
- [TEST REPORT LINK](https://yuliia-dronova.github.io/layout_catalog/report/html_report/)

### CODE REVIEW

**Review by Ihor-Karpyn — CHANGES_REQUESTED** [review]
checklist p13

**Review by ivan-kadykalo — CHANGES_REQUESTED** [review]
Fix your tests
image
image

**Comment by yuliia-dronova** [comment]
> Fix your tests image image

Padding were fixed, but there are still some minor diffs from test.. :(

image

**Review by Ihor-Karpyn — CHANGES_REQUESTED** [review]
checklist p13
image

**Review by Ihor-Karpyn — APPROVED** [review]

**Comment by yuliia-dronova** [comment]
> checklist p13 image

finally I've found that facepalm mistake)) Now it works, thank you.

**Review by alexandra-protyanova — APPROVED** [review]

**Review by ivan-kadykalo — APPROVED** [review]

**Pull request closed without merging**
