### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Viiktorrr**
- [DEMO LINK](https://Viiktorrr.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Viiktorrr.github.io/layout_catalog/report/html_report/)
- not for viewing

### CODE REVIEW

**Comment by Viiktorrr** [comment]
- [DEMO LINK](https://Viiktorrr.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Viiktorrr.github.io/layout_catalog/report/html_report/)

**Comment by Viiktorrr** [comment]
- [DEMO LINK](https://Viiktorrr.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Viiktorrr.github.io/layout_catalog/report/html_report/)

**Comment by Viiktorrr** [comment]
- [DEMO LINK](https://Viiktorrr.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Viiktorrr.github.io/layout_catalog/report/html_report/)
- 3-

**Comment by Viiktorrr** [comment]
- [DEMO LINK](https://Viiktorrr.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Viiktorrr.github.io/layout_catalog/report/html_report/)

**Comment by Viiktorrr** [comment]
- [DEMO LINK](https://Viiktorrr.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Viiktorrr.github.io/layout_catalog/report/html_report/)

**Comment by Viiktorrr** [comment]
- [DEMO LINK](https://Viiktorrr.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Viiktorrr.github.io/layout_catalog/report/html_report/)

**Comment by Viiktorrr** [comment]
- [DEMO LINK](https://Viiktorrr.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Viiktorrr.github.io/layout_catalog/report/html_report/)
-

**Comment by Viiktorrr** [comment]
- [DEMO LINK](https://Viiktorrr.github.io/layout_catalog/)
- [TEST REPORT LINK](https://Viiktorrr.github.io/layout_catalog/report/html_report/)

**Comment by Viiktorrr** [comment]
Знімок екрана 2022-10-05 о 17 43 51

**Comment by Largoxoxo** [comment]
1. Your pull request status is 'closed', you should re-'open' it (if possible) or create new pull request.
2. Link doesn't work.
3. You have 2 similar files: variables.scss (in utils folder) and variebls.scss (in styles folder).
4.  You have 2 mixin files, one in utils folder and one in styles folder.
5.  Same story with 2 functions.scss files.
6. 2 similar folders bloks and blocks. 
7. You don't have content class in your index.html but you have content.scss with content class in it.
8. I couldn't find star-box class from style-stars.scss in your index.html

**Pull request closed without merging**
