### PR TITLE
Full pull request

### PR DESCRIPTION
**Pull request by AleksanderPl**
[DEMO LINK](https://aleksanderpl.github.io/layout_catalog/)
[TEST REPORT LINK](https://aleksanderpl.github.io/layout_catalog/report/html_report/)

### CODE REVIEW

**Comment by alexandra-protyanova** [comment]
Снимок экрана 2022-07-15 в 11 42 58
remove <> from the link

**Review by valerii-derkach — COMMENTED** [review]
your pull request is closed, please open it for review
image

**Comment by AleksanderPl** [comment]
I have second Pull request. And the problem is same (npm test crlf). But in webstorm (or in vs code) that problem is absent.
https://github.com/mate-academy/layout_catalog/pull/1751

**Comment by AleksanderPl** [comment]
I have second Pull request. And the problem is same (npm test crlf). But in webstorm (or in vs code) that problem is absent.
https://github.com/mate-academy/layout_catalog/pull/1751


> your pull request is closed, please open it for review image

**Pull request closed without merging**
