### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by yurii-krymskiy**
- [DEMO LINK](https://yurii-krymskiy.github.io/layout_catalog/)
- [TEST REPORT LINK](https://yurii-krymskiy.github.io/layout_catalog/report/html_report/)

### CODE REVIEW

**Review by slavanosatskyi — CHANGES_REQUESTED** [review]
it should be 4 products per row, even on a bigger screen

Screenshot 2023-04-25 at 18 00 31

**Review by vlad-demchuk — CHANGES_REQUESTED** [review]
center the catalog
image

try to fix tests

**Review by anstsot — CHANGES_REQUESTED** [review]
Looks good from the code perspective but the tests are still failed. Have you forgotten to update? 
If you have any questions, feel free to ask them in the chat

**Comment by yurii-krymskiy** [comment]
I don't know but I have maybe troubles with Backstop , for instance when I delete it(backstop) and write npm test ,than there are could be 8 failed, when I delete second time backstop and write npm test there could be 2 failed or without failures

**Review by anstsot — CHANGES_REQUESTED** [review]
Please write in the `fe_chat` to get mentors to help you with tests. It's hard to track here new messages

**Pull request closed without merging**
